apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: templatedirs.crdtest.example.com
spec:
  group: crdtest.example.com
  versions:
  - name: v1
    served: true
    storage: true
  version: v1
  scope: Namespaced
  names:
    plural: templatedirs
    singular: templatedir
    kind: TemplateDir
    shortNames:
    - t
